### ISSUE TITLE
Connecting devices/sensors to Volcap

### ISSUE THREAD

**Issue by ganeshoys** [VCL3D/VolumetricCapture#50]
Hi team, 

 Greeting of the day,  
  as mention in the "https://vcl3d.github.io/VolumetricCapture/docs/configure/", i have created the device_repository.json, and i do have some issue also, as mention in the  site, while opening the VolCap.exe. the device name will automatically listed in VolCap.exe as per device_repository. but its not showing the List of  device.
![Volcap.exe_Snapshot](https://user-images.githubusercontent.com/78359221/114367980-990d8100-9b9a-11eb-801f-5f06c68a0aa3.JPG), 

while checking in intel_nuc_led_utils ( Eye-NUC). am getting this Exception
![intel_nuc_led_utils](https://user-images.githubusercontent.com/78359221/114368990-92333e00-9b9b-11eb-8958-d0380eb5d6b7.PNG)

i was able to find the log from the "remote_eye_service", the log pasted below.
"WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [12-04-2021 02:05:23 PM] : Activation of C:\Capturer\remote_eye_service\remote_eye_service.application has started.
	* [12-04-2021 02:05:23 PM] : Processing of deployment manifest has successfully completed.
	* [12-04-2021 02:05:23 PM] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [12-04-2021 02:05:23 PM] System.Deployment.Application.InvalidDeploymentException (Zone)
		- Deployment and application do not have matching security zones.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)"

Thank you
Ganesh

**Comment by ganeshoys** [comment]
Please Guide me to Connect the Setup 
thank you 
ganesh

**Comment by ankarako** [comment]
Hi @ganeshoys and thank you for your interest in our work!

It seems that there is a problem with the `remote_eye_service`. 
1.May I ask if you the model of you NUC-PC? Does it have a led ring on its front plate?

**Comment by ganeshoys** [comment]
Thank you @ankarako, 

My NUC's model number is "nuc8i5beh". i think this model doesn't have Ring light 
Have Tried the manual Connection. but not yet connected while in pinging from EYE, Remote_eye_Service -Sent Hello, in master computer i didn't received any response to it

**Comment by ankarako** [comment]
Just to make sure,

To connect manually each `eye` to `volcap`:
1. First, open `volcap.exe`
2. Then run the cli command (described [here](https://vcl3d.github.io/VolumetricCapture/docs/eyes/#manual-sensor-connection)) on each NUC

**Comment by ganeshoys** [comment]
@ankarako  thank you

 i hope i did this .. let me share you the Help Screen shot on Eye
![image](https://user-images.githubusercontent.com/78359221/114377294-1d183680-9ba4-11eb-93cd-7e82f974289c.png)

i do have  question 
My Master (controller IP is 192.168.1.6) does this doing any issue.

**Comment by ankarako** [comment]
You will have to run `remote_eye_k4a.exe --address 192.168.1.6`

**Comment by ganeshoys** [comment]
Ya Tried it too...

**Comment by ankarako** [comment]
Can you open a command line on the main workstation and type `ipconfig`?

1. How many network adapters are there?
2. When `volcap` starts, does the ip displayed there, match any of the ips displayed with `ipconfig`?

**Comment by ganeshoys** [comment]
Thank you @ankarako.
 my computer as only one network port
![image](https://user-images.githubusercontent.com/78359221/114380532-cf9dc880-9ba7-11eb-9b6d-b6ec76bea406.png)

  I have tried running eye on the same computer and made remote_eye_k4a.exe --address 192.168.1.6 but I didn't  got any device listed on Volcap.exe

![image](https://user-images.githubusercontent.com/78359221/114380699-f8be5900-9ba7-11eb-8f22-a206a5514c1a.png)

**Comment by ankarako** [comment]
Hmmm, have you opened the ports described [here](https://vcl3d.github.io/VolumetricCapture/docs/software/#rabbitmq-setup) and [here](https://vcl3d.github.io/VolumetricCapture/docs/software/#service--eye)?

**Comment by ganeshoys** [comment]
Yes Ankarako
![image](https://user-images.githubusercontent.com/78359221/114381455-c5c89500-9ba8-11eb-8e60-b8b9c44bb711.png)

**Comment by ankarako** [comment]
Hi again,

Are the NUCs and the main PC connected on the same LAN via a dedicated switch?

**Comment by zuru** [comment]
Closing due to inactivity, feel free to re-open to follow up if necessary.

**Comment by ganeshoys** [comment]
@zuru  sorry for the delay reply. .. its been lockdown these days in india. so we are able to try and reply... thank you for closing the questions..
@ankarako sorry for the delay reply, will try the dedicated switch and let u know

**Comment by ganeshoys** [comment]
hi  Team. i need some help on calibration, i dont know where am missing..
 the process which we followed
 01. My python version is 3.6 and installed using  python.exe install.py.
 02.  made boxes as mention size on site 
![image](https://user-images.githubusercontent.com/78359221/124592712-5dbdde00-de7b-11eb-9aa4-998885c59ec1.png)

and followed https://www.youtube.com/watch?v=_0MIxWAE6bw (VCL3D-VolCap: Calibrating 3 devices setting 1), 

The Error 
![image](https://user-images.githubusercontent.com/78359221/124592324-f6079300-de7a-11eb-97d6-d846662598fe.png)

**Comment by zuru** [comment]
Please see if #53 or #42 help and let us know otherwise
